version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - pip install --upgrade pip
      - pip install -r requirements.txt -t lib
      - echo "Packaging Lambda requirements..."
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - lib/**/*
